version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-html-to-odt-app-20240202.040927
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - __SOURCE__:/input/
      - __SOURCE__:/output/
    # restart: on-failure